os: osx
osx_image: xcode8
language: objective-c
xcode_workspace: SwiftTemplateFramework.xcworkspace
xcode_scheme: SwiftTemplateFramework
xcode_sdk: iphonesimulator10.1
script: 
  - xctool -workspace SwiftTemplateFramework.xcworkspace -scheme SwiftTemplateFramework -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xctool test -workspace SwiftTemplateFramework.xcworkspace -scheme SwiftTemplateFrameworkTests -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO