source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.1'
use_frameworks!
inhibit_all_warnings!

def required_pods

pod 'SwiftTemplateFramework', :git => 'https://github.com/Reedyuk/SwiftTemplateFramework.git'

end

target "SimpleNetworkExample" do
    required_pods
    post_install do |installer|
        installer.pods_project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['ENABLE_BITCODE'] = 'NO'
                config.build_settings['CLANG_ENABLE_OBJC_WEAK'] ||= 'YES'
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.1'
                if config.name == 'Debug'
                    config.build_settings['OTHER_SWIFT_FLAGS'] = '-DDEBUG'
                end
            end
        end
    end
end

